---
# handlers file for minio

- name: reload minio systemd
  systemd:
    name: minio
    daemon_reload: True

- name: restart minio
  service:
    name: minio
    state: restarted
  notify: Check MinIO WebUI

- name: Check MinIO WebUI
  uri:
    url: "{{ minio_connection_type }}://{{ minio_hostname }}:{{ minio_server_port }}/minio/login"
    status_code: 200
    headers:
      User-Agent: "Mozilla/5.0"
    validate_certs: false
  register: login_page
  until: login_page.status == 200
  retries: 10
  delay: 1
