---
scenario:
  name: default

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: test-docker-centos7-minio
    image: quay.io/minio/centos-systemd:7
    privileged: true
    pre_build_image: true
    command: /sbin/init
    published_ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - rhel_family

  - name: test-docker-ubuntu2004-minio
    image: quay.io/minio/ubuntu-systemd:20.04
    command: /sbin/init
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - debian_family

provisioner:
  name: ansible
  log: true
  options:
    diff: True
    v: True
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    verify: ../resources/tests/verify.yml

lint: |
  set -e
  yamllint .

verifier:
  name: ansible
