---
name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint and Molecule
        run: |
          pip3 install --upgrade pip wheel && \
          pip3 install --upgrade cryptography cffi && \
          pip3 install ansible-core==2.13.2 && \
          pip3 install ansible==6.1.0 ansible-lint==6.3.0 yamllint && \
          pip3 install molecule molecule-containers molecule-docker molecule-podman molecule-ec2

          yamllint . -c .yamllint
          ansible-lint -x fqcn-builtins,var-spacing -c .ansible-lint

          molecule test -s default
